---
- name: Install requirements
  hosts: routers
  become: true
  tasks:
  - name: Install Quagga, Quagga-docs and Pip3
    yum:
      name:
        - quagga
        - quagga-doc
        - python3-pip
      state: present
  - name: Install pytest
    pip:
      name: pytest
      state: present
      executable: pip3
