# apt-install-services.yml
---
- hosts: routers
  become: true
  tasks:
  - name: Install Quagga and Quagga-docs
    yum:
      name:
        - quagga
        - quagga-doc
      state: present
  - name: Install pip3
    yum:
      name:
        - python-pip3
      state: present
  - name: Install pytest
    pip:
      name: pytest
      state: present
      executable: pip3