- hosts: all
  tasks:
    - name: install Quagga on Debian based distros
      apt:
        name: quagga
        state: present
        update_cache: true
      become: true
      when: ansible_os_family == 'Debian'

    - name: install Quagga on RHEL based distros
      yum:
        name: quagga
        state: present
        update_cache: true
      become: true
      when: ansible_os_family == 'RedHat'